multi_step_lstm_config = {  'batch_size': 256,
                            'n_epochs': 100,
                            'dropout': 0.1,
                            'look_back': 20,
                            'look_ahead': 1,
                            #'layers':{'input': 1, 'hidden1':20, 'hidden2':5,  'output': 1},
                            #'layers':{'input': 1, 'hidden1': 200, 'hidden2': 80, 'hidden3': 40, 'hidden4': 10,'output': 1},
                            'layers': {'input': 4, 'hidden1': 16, 'output': 4},
                            'loss': 'mse',
                            #'optimizer': 'adam',
                            'train_test_ratio': 0.7,
                            'shuffle': False,
                            'validation': False,
                            'learning_rate': .02,
                            'patience':20,
                           }