multi_step_lstm_config = {  'batch_size': 256,
                            'n_epochs': 100,
                            'dropout': 0.1,
                            'look_back': 20,
                            'look_ahead': 1,
                            # 'layers':{'input': 1, 'hidden1':20, 'hidden2':5,  'output': 1},
                            'layers': {'input': 50, 'hidden1': 50, 'hidden2': 50, 'output': 1},
                            'loss': 'mse',
                            'metrics': ["accuracy"],
                            # 'optimizer': 'adam',
                            'train_test_ratio': 0.7,
                            'train_validation_ratio': 0.2,
                            'shuffle': False,
                            'validation': False,
                            'learning_rate': .02,
                            'patience': 20,
                           }